
const int doubleSireneSize = 3;
const int doubleSireneTempo = 120;
const int doubleSirene [doubleSireneSize][3] =
{
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE }
};

const int standardSireneSize = 7;
const int standardSireneTempo = 140;
const int standardSirene [standardSireneSize][3] =
{
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_FAd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE }
};

const int darkSideOfTheMoonSize = 5;
const int darkSideOfTheMoonTempo = 120;
const int darkSideOfTheMoon [darkSideOfTheMoonSize][3] =
{
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_2, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_RONDE }
};

const int smokeOnTheWaterSize = 18;
const int smokeOnTheWaterTempo = 100;
const int smokeOnTheWater [smokeOnTheWaterSize][3] =
{
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },

  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_DOd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_BLANCHE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_NOIRE }
};

const int highwayToHellSize = 25;
const int highwayToHellTempo = 125;
const int highwayToHell [highwayToHellSize][3] =
{
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE }
};

const int hellsBellsSize = 32;
const int hellsBellsTempo = 100;
const int hellsBells [hellsBellsSize][3] =
{
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },

  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE }
  //{ PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_RONDE }
};

const int iWantYouBackSize = 31;
const int iWantYouBackTempo = 102;
const int iWantYouBack [iWantYouBackSize][3] =
{
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_NOTE_SI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_REd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_DOd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE },

  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_DOd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_REd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_DOd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_REd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },


  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  //{ PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_NOIRE }
};

const int themeRencontre3TypeSize = 6;
const int themeRencontre3TypeTempo = 102;
const int themeRencontre3Type [themeRencontre3TypeSize][3] =
{
  { PASSIVE_BUZZER_NOTE_FAd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_MI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 1, PASSIVE_BUZZER_NOTE_BLANCHE }
};

const int themeStarTrekIntroSize = 15;
const int themeStarTrekIntroTempo = 180;
const int themeStarTrekIntro [themeStarTrekIntroSize][3] =
{
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_REd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_RONDE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_RONDE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_RONDE }
};

const int themeStarTrekSize = 21;
const int themeStarTrekTempo = 102;
const int themeStarTrek [themeStarTrekSize][3] =
{
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_REd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_LAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOLd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_RONDE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },

  { PASSIVE_BUZZER_NOTE_FAd, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_NOIRE },
  { PASSIVE_BUZZER_NOTE_FA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_NOTE_REd, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_BLANCHE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_RONDE }
};

const int themeStarWarsSize = 31;
const int themeStarWarsTempo = 180;
const int themeStarWars [themeStarWarsSize][3] =
{
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_5, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SOL, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_BLANCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_DBL_CROCHE },
  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_RE, PASSIVE_BUZZER_OCTAVE_4, PASSIVE_BUZZER_NOTE_NOIRE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_SI, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_DO, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_CROCHE },
  { PASSIVE_BUZZER_NOTE_LA, PASSIVE_BUZZER_OCTAVE_3, PASSIVE_BUZZER_NOTE_BLANCHE },

  { PASSIVE_BUZZER_SILENT, 0, PASSIVE_BUZZER_NOTE_BLANCHE }
};
